/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Codigo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author EQUINOX
 */
public class VentanaCronometro extends javax.swing.JFrame {

    private Timer tiempo;
    private int centesimaSegundo=0, segundo=0, minuto=0, hora=0;
    private ActionListener acciones=new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            centesimaSegundo++;
            if (centesimaSegundo==100) {
                segundo++;
                centesimaSegundo=0;
            }
            if (segundo==60) {
                minuto++;
                segundo=0;
            }
            if (minuto==60) {
                hora++;
                minuto=0;
            }
            actualizarTiempo();
        }
    };
    
    private void actualizarTiempo(){
        String texto = (hora<=9?"0":"")+hora+":"+(minuto<=9?"0":"")+minuto+":"+(segundo<=9?"0":"")+segundo+":"+(centesimaSegundo<=9?"0":"")+centesimaSegundo;
        JLcronometro.setText(texto);
    }
    
    public VentanaCronometro() {
        
        initComponents();
        setLocationRelativeTo(null);
        tiempo=new Timer(10,acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        botonIniciar = new javax.swing.JButton();
        botonPausar = new javax.swing.JButton();
        botonDetener = new javax.swing.JButton();
        JLimagen = new javax.swing.JLabel();
        JLtitulo = new javax.swing.JLabel();
        JLcronometro = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRONOMETRO");
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonIniciar.setBackground(new java.awt.Color(153, 153, 153));
        botonIniciar.setText("INICIAR");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });
        panel.add(botonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 30));

        botonPausar.setBackground(new java.awt.Color(153, 153, 153));
        botonPausar.setText("PAUSAR");
        botonPausar.setEnabled(false);
        botonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausarActionPerformed(evt);
            }
        });
        panel.add(botonPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 30));

        botonDetener.setBackground(new java.awt.Color(153, 153, 153));
        botonDetener.setText("DETENER");
        botonDetener.setEnabled(false);
        botonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerActionPerformed(evt);
            }
        });
        panel.add(botonDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 30));

        JLimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/crono.png"))); // NOI18N
        JLimagen.setText("jLabel1");
        panel.add(JLimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, 200));

        JLtitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JLtitulo.setForeground(new java.awt.Color(204, 0, 0));
        JLtitulo.setText("CRONOMETRO");
        panel.add(JLtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        JLcronometro.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        JLcronometro.setForeground(new java.awt.Color(0, 0, 153));
        JLcronometro.setText("00:00:00:00");
        panel.add(JLcronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 200, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        panel.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        tiempo.start();
        botonIniciar.setEnabled(false);
        botonIniciar.setText("REANUDAR");
        botonPausar.setEnabled(true);
        botonDetener.setEnabled(true);
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void botonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausarActionPerformed
        tiempo.stop();
        botonIniciar.setEnabled(true);
        botonPausar.setEnabled(false);
    }//GEN-LAST:event_botonPausarActionPerformed

    private void botonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerActionPerformed
        if (tiempo.isRunning()) {
            tiempo.stop();
            botonIniciar.setEnabled(true);
        }
        botonIniciar.setText("INICIAR");
        botonPausar.setEnabled(false);
        botonDetener.setEnabled(false);
        
        centesimaSegundo=0;
        segundo=0; 
        minuto=0; 
        hora=0;
        
        actualizarTiempo();
    }//GEN-LAST:event_botonDetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCronometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLcronometro;
    private javax.swing.JLabel JLimagen;
    private javax.swing.JLabel JLtitulo;
    private javax.swing.JButton botonDetener;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonPausar;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    public void holaM(){
        
    }
}
